### PR TITLE
Make CLI in line with intended default for increment_micro

### LINKED ISSUE #326: Bug? Bump pre-release from released version
Thanks @carstencodes for your great work on this!

I'm getting the following output

```
pdm bump pre-release --pre alpha
Performing increment of version: 0.5.2 -> 0.5.2a1
```

Is this behaviour intended? I would have thought that, if I am on version 0.5.2 and I bump to the next pre-release, I should go to 0.5.3a1 (i.e. the pre-release for the next version) rather than 0.5.2a1 (which would be a pre-release for a version which has already been released, namely 0.5.2).

### PR DESCRIPTION
**Pull request by znichollscr**
@carstencodes I think this would fix #326,
but I'm not certain about any side effects.

A different solution would be to use store_const
and have different None handling, see e.g.
https://docs.python.org/3/library/argparse.html.
Again, not sure of side effects.

### CODE REVIEW

**Comment by znichollscr** [comment]
Hmm the fact that the tests still pass also suggest there's a missing test case somewhere..

**Comment by carstencodes** [comment]
Yeah, tests are not fully covered yet.

Currently, changing the command-line argument would introduce a breaking change. 

Sorry for being a little cautious about this, but I might find a workaround using meta-vars...

Give me a day or two

**Comment by znichollscr** [comment]
No problem, take your time

**Comment by znichollscr** [comment]
As far as I could tell, the CLI is setting the increment_micro option so the defaults deeper within the codebase are just overwritten

**Comment by carstencodes** [comment]
Ah, as the smallest supported python version is 3.9, the `argparse.BooleanOptionalAction` is available (cf [manual](https://docs.python.org/3/library/argparse.html#action)):

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--foo', action=argparse.BooleanOptionalAction)  # Added in version 3.9.
parser.parse_args(['--no-foo'])
Namespace(foo=False)
```

This should be combinable with [default values](https://docs.python.org/3/library/argparse.html#default).

So, a possible solution would be

```
sub_parser.add_argument(
            "--micro",
            action=argparse.BooleanOptionalAction,
            dest="increment_micro",
            help="When setting pre-release, specifies "
            + "whether micro version shall "
            + "be incremented as well.",
           default=True,
        )
```

I could give it a try, when I'm home tomorrow.

**Comment by znichollscr** [comment]
Nice. You might need to get rid of `default=True` too, time will tell

**Comment by carstencodes** [comment]
Unfortunately, the BooleanOptionalAction is still a bit buggy, but I managed it to setup a working implementation with a mutual exclusive argument group.

**Comment by znichollscr** [comment]
Seems to work in the quick test I did, thanks!

**Pull request merged**
